name: share_extend
description: A Flutter plugin for Android and iOS for sharing text, image, video and file with system ui.
version: 2.0.1
author: zhouteng <qfszyq@gmail.com>
homepage: https://github.com/zhouteng0217/ShareExtend

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.zt.shareextend
        pluginClass: ShareExtendPlugin
      ios:
        pluginClass: ShareExtendPlugin
