name: assecontservices_example
description: Demonstrates how to use the assecontservices plugin.


version: 3.1.2+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  shimmer: ^2.0.0
  brasil_fields: ^1.3.1
  assecontservices:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

