name: assecontservices_example
description: Demonstrates how to use the assecontservices plugin.


version: 3.1.2+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  flutter_local_notifications: ^12.0.4
  timezone: ^0.9.0
  flutter_native_timezone: ^2.0.0
  provider:
  http: ^0.13.5

  url_launcher: ^6.1.7
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2

  shared_preferences: ^2.0.15

  intl: ^0.17.0

  datetime_picker_formfield: ^2.0.1
  shimmer: ^2.0.0
  auto_animated: ^3.1.0
  brasil_fields: ^1.7.0
  assecontservices:
    path: ../

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/imagens/