name: assecontservices
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <=4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.5

  flutter_awesome_alert_box: ^2.1.1
  top_snackbar_flutter: ^3.1.0

  sqflite: ^2.3.0 #^2.0.2
  sqflite_common_ffi: ^2.3.0+3
  sqflite_common_ffi_web: ^0.4.0

  responsive_framework: ^1.1.1
  ###^0.2.0

  http: ^1.1.0

  intl: any #^0.18.1

  image_picker: ^1.0.4
  filesystem_picker: ^3.1.0 #^2.0.2

  local_auth: ^2.1.7

  photo_view: ^0.14.0

  geocoding: ^2.1.1
  location: ^5.0.3
  #$google_maps_flutter: ^2.2.5

  url_launcher: ^6.1.14

  flutter_carousel_slider: ^1.1.0

  flutter_calendar_week:
    git:
      url: https://github.com/PRETOLIO-DEV/calendario_semanal.git
      ref: web

  tutorial:
    git:
      url: https://github.com/pretolio/tutorial.git
      ref: main

  #charts_flutter_new: ^0.12.0
  charts_flutter: #^0.12.0
    git:
      url: https://github.com/pretolio/charts_flutter.git
      ref: main

  #webcontent_converter: ^0.0.7+1
  flutter_html_to_pdf: ^0.7.0

  syncfusion_flutter_pdfviewer: ^23.1.39
  #syncfusion_flutter_pdfviewer:
  #  git:
  #    url: https://github.com/pretolio/syncfusion_flutter_pdfviewer.git
  #    ref: main

  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  external_path: ^1.0.3

  cpf_cnpj_validator: ^2.0.0

  #open_file_safe: ^3.2.3

  share_extend: ^2.0.0

  universal_io: ^2.2.2
  universal_html: ^2.2.4

  connectivity_plus: any
  package_info_plus: any #^3.0.2 #^1.4.2
  #device_info_plus: ^9.0.0
  safe_device: ^1.1.4

  brasil_fields: ^1.14.0
  datetime_picker_formfield: ^2.0.1

  in_app_review: ^2.0.8
  launch_review: ^3.0.1

  #store_launcher: ^1.0.1

  auto_size_text: ^3.0.0

  schedulers: ^1.0.1

  device_preview: ^1.1.0

dependency_overrides:
  #intl: ^0.17.0


dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/imagens/
    - pubspec.yaml
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.assecont.servicos.assecontservices
        pluginClass: AssecontservicesPlugin
      ios:
        pluginClass: AssecontservicesPlugin
      windows:
        pluginClass: AssecontservicesPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
