name: assecontservices
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <=4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2

  flutter_awesome_alert_box: ^2.1.1
  top_snackbar_flutter: ^3.1.0

  sqflite: ^2.3.3+1 #^2.0.2
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.5+2

  responsive_framework: ^1.5.1
  ###^0.2.0

  http: ^1.2.2

  intl: any #^0.18.1

  image_picker: ^1.1.2
  filesystem_picker: ^4.1.0 #^2.0.2

  local_auth: ^2.3.0

  photo_view: ^0.15.0

  #$google_maps_flutter: ^2.2.5

  url_launcher: ^6.3.0

  flutter_carousel_slider: ^1.1.0

  flutter_calendar_week:
    git:
      url: https://github.com/PRETOLIO-DEV/calendario_semanal.git
      ref: web

  tutorial:
    git:
      url: https://github.com/pretolio/tutorial.git
      ref: main

  #charts_flutter_new: ^0.12.0
  charts_flutter: #^0.12.0
    git:
      url: https://github.com/pretolio/charts_flutter.git
      ref: main

  #webcontent_converter: ^0.0.7+1
  #flutter_html_to_pdf: ^0.7.0
  flutter_html_to_pdf_plus: ^0.1.0

  #syncfusion_flutter_pdfviewer: ^23.1.39
  syncfusion_flutter_pdfviewer: ^26.2.13

  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  external_path: ^2.0.1

  cpf_cnpj_validator: ^2.0.0

  #open_file_safe: ^3.2.3

  share_extend:
    path: packages/share_extend

  universal_io: ^2.2.2
  universal_html: ^2.2.4

  connectivity_plus: ^6.0.5
  package_info_plus: any #^3.0.2 #^1.4.2
  #device_info_plus: ^9.0.0

  safe_device: #^1.1.4
    git:
      url: https://github.com/pretolio/safe_device.git
      ref: main

  brasil_fields: ^1.15.0
  datetime_picker_formfield_new: ^2.1.0

  in_app_review: ^2.0.9
  launch_app_store: ^1.1.2

  #store_launcher: ^1.0.1

  auto_size_text: ^3.0.0
  auto_animated: ^3.2.0
  shimmer: ^3.0.0

  schedulers: ^1.0.1

  device_preview: ^1.2.0


dependency_overrides:

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/imagens/
    - pubspec.yaml
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.assecont.servicos.assecontservices
        pluginClass: AssecontservicesPlugin
      ios:
        pluginClass: AssecontservicesPlugin
      windows:
        pluginClass: AssecontservicesPlugin


